#!/usr/bin/python
# Transform Nmap xml to Excel
# Author: Benjamin Kellermann, License: GPLv3
import xml.etree.ElementTree as ET
from openpyxl import Workbook
import sys
if len(sys.argv) < 3:
    print "Usage: ",sys.argv[0] ," scan1.xml [scan2.xml [scan...]] outfile.xlsx" 
    exit(0)

target = sys.argv.pop()

ports = []
for f in sys.argv[1:]:
    xml = ET.parse(f)
    root = xml.getroot()


    for host in root.iter('host'):
        address = host.find('address').get('addr')
        hostname = []
        for h in host.find('hostnames').iter('hostname'):
            hostname.append(h.get('name'))

        for p in host.find('ports').iter('port'):
            port = str(p.get('portid')) + "/" + p.get('protocol')
            reason = p.find('state').get('reason')
            product = []
            if p.find('service') is not None:
                service = p.find('service').get('name')
                product.append(p.find('service').get('product'))
                product.append(p.find('service').get('version'))
                product.append(p.find('service').get('extra'))
                product = [x for x in product if x is not None]
            else:
                service = ""
            ports.append([address, ", ".join(hostname), port, reason, service, " ".join(product)])


# Save the file
# Open up a new excel file
wb = Workbook()

ws = wb.worksheets[0]
ws.title = "Services"
ws.append(["Adresse","Hostname", "Port", "Erkennung", "Service", "Product"])
for entry in ports:
    ws.append(entry)
wb.save(target)
